// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvrwjvdadyxbphylnudi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cndqdmRhZHl4YnBoeWxudWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTU3NzksImV4cCI6MjA2ODkzMTc3OX0.GiGDzUQGBlLIHzpWHuGZPRMC8pv7TglUxYknzk_mGP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});